name: Publish Docker image

on:
  push:
    branches:  
      - master 
      - develop
      - feature/*
      - hotfix/*

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 'Create env file'
      run: |
        touch .env
        echo NEXT_PUBLIC_SANITY_STUDIO_PROJECT_ID=${{ secrets.SANITY_STUDIO_PROJECT_ID }} >> .env
        echo NEXT_PUBLIC_SANITY_STUDIO_URL=${{ secrets.SANITY_STUDIO_URL }} >> .env
        echo NEXT_PUBLIC_SANITY_STUDIO_URL=${{ secrets.SANITY_STUDIO_URL }} >> .env
        echo NEXT_PUBLIC_SANITY_STUDIO_DATASET=production >> .env
        echo NEXT_PUBLIC_SANITY_STUDIO_STEGA_ENABLED=false >> .env

    - name: Determine tag
      run: |
        if [ "$GITHUB_REF" == "refs/heads/master" ]; then
          TAG="latest"
        elif [ "$GITHUB_REF" == "refs/heads/develop" ]; then
          TAG="dev"
        else
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          TAG=$(echo "$BRANCH_NAME" | tr '/' '-')
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "Using tag: $TAG"

    - name: Build and push image
      uses: docker/build-push-action@v6
      # env: 
      #   TAG: $TAG
      with:
        context: .
        platforms: linux/arm64,linux/amd64
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/portfolio:${{env.TAG}}
